name: Build android aab to MoveIn
on:
  workflow_dispatch:
    inputs:
      enableMockApi:
        description: 'enable mock api'
        type: boolean
        required: false
      apiUrl:
        description: 'api url'
        type: string
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build android aab to MoveIn
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Install Yarn
        run: corepack prepare yarn@* --activate
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(corepack yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - run: corepack yarn
      - run: corepack yarn codegen
      
      - name: Make Gradle executable
        run: chmod +x ./android/gradlew
        working-directory: ./apps/move-in
      - name: Update build number
        run: corepack yarn cap-set-version -b ${{ github.run_number }}
        working-directory: ./apps/move-in
      - run: corepack yarn build-aab
        env: 
          VITE_ENABLE_MOCK_API: ${{ inputs.enableMockApi }}
          VITE_API_URL: ${{ inputs.apiUrl }}
          ANDROID_KEYSTORE_KEY_ALIAS: key
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.MOVE_IN_ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.MOVE_IN_ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_PATH: release-key-store.jks
        working-directory: ./apps/move-in

      - uses: actions/upload-artifact@v4
        with:
          name: move-in-${{ github.run_number }}
          path: apps/move-in/android/app/build/outputs/bundle/release/app-release-signed.aab
